#!/bin/bash

mv ./main.py ./visma
python3 setup.py sdist bdist_wheel
mv ./visma/main.py ./

if [ "$1" == "upload" ];
    then
    twine upload --repository-url https://test.pypi.org/legacy/ dist/*
fi
