#!/bin/bash

echo "Python Syntax Test..."
pylama
echo "Python Modules Test..."
if [ "$1" != "" ] && [ $1 != "report" ];
then
    coverage run --source ./ -m pytest $1 -v
else
    coverage run --source ./ -m pytest -v
fi
coverage report
coverage html
if [ "$1" == "report" ] || [ "$2" == "report" ];
    then
    nohup xdg-open ./htmlcov/index.html &
fi
